[package]
name = "anvil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.sdl2]
version = "0.36"
default-features = false
features = ["ttf"]

[dependencies]
hecs = "0.10.4"
rand = "0.8.5"